/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TariffRouteImport } from './routes/tariff'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as ResortAmenitiesRouteImport } from './routes/resort-amenities'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NearbyAttractionsRouteImport } from './routes/nearby-attractions'
import { Route as InfinityPoolRouteImport } from './routes/infinity-pool'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as AdventureActivitiesRouteImport } from './routes/adventure-activities'
import { Route as AdventureRouteImport } from './routes/adventure'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VillasIndexRouteImport } from './routes/villas/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as VillasSlugRouteImport } from './routes/villas/$slug'
import { Route as OffersMonsoonRouteImport } from './routes/offers.monsoon'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BlogCategoryCatRouteImport } from './routes/blog/category.$cat'

const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TariffRoute = TariffRouteImport.update({
  id: '/tariff',
  path: '/tariff',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ResortAmenitiesRoute = ResortAmenitiesRouteImport.update({
  id: '/resort-amenities',
  path: '/resort-amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyAttractionsRoute = NearbyAttractionsRouteImport.update({
  id: '/nearby-attractions',
  path: '/nearby-attractions',
  getParentRoute: () => rootRouteImport,
} as any)
const InfinityPoolRoute = InfinityPoolRouteImport.update({
  id: '/infinity-pool',
  path: '/infinity-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventureActivitiesRoute = AdventureActivitiesRouteImport.update({
  id: '/adventure-activities',
  path: '/adventure-activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventureRoute = AdventureRouteImport.update({
  id: '/adventure',
  path: '/adventure',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VillasIndexRoute = VillasIndexRouteImport.update({
  id: '/villas/',
  path: '/villas/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const VillasSlugRoute = VillasSlugRouteImport.update({
  id: '/villas/$slug',
  path: '/villas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersMonsoonRoute = OffersMonsoonRouteImport.update({
  id: '/monsoon',
  path: '/monsoon',
  getParentRoute: () => OffersRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoryCatRoute = BlogCategoryCatRouteImport.update({
  id: '/blog/category/$cat',
  path: '/blog/category/$cat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/accommodation': typeof AccommodationRoute
  '/adventure': typeof AdventureRoute
  '/adventure-activities': typeof AdventureActivitiesRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/experiences': typeof ExperiencesRoute
  '/family': typeof FamilyRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/gallery': typeof GalleryRoute
  '/infinity-pool': typeof InfinityPoolRoute
  '/nearby-attractions': typeof NearbyAttractionsRoute
  '/offers': typeof OffersRouteWithChildren
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/resort-amenities': typeof ResortAmenitiesRoute
  '/restaurant': typeof RestaurantRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tariff': typeof TariffRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/weddings': typeof WeddingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/offers/monsoon': typeof OffersMonsoonRoute
  '/villas/$slug': typeof VillasSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/villas/': typeof VillasIndexRoute
  '/blog/category/$cat': typeof BlogCategoryCatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/accommodation': typeof AccommodationRoute
  '/adventure': typeof AdventureRoute
  '/adventure-activities': typeof AdventureActivitiesRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/experiences': typeof ExperiencesRoute
  '/family': typeof FamilyRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/gallery': typeof GalleryRoute
  '/infinity-pool': typeof InfinityPoolRoute
  '/nearby-attractions': typeof NearbyAttractionsRoute
  '/offers': typeof OffersRouteWithChildren
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/resort-amenities': typeof ResortAmenitiesRoute
  '/restaurant': typeof RestaurantRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tariff': typeof TariffRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/weddings': typeof WeddingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/offers/monsoon': typeof OffersMonsoonRoute
  '/villas/$slug': typeof VillasSlugRoute
  '/blog': typeof BlogIndexRoute
  '/villas': typeof VillasIndexRoute
  '/blog/category/$cat': typeof BlogCategoryCatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/accommodation': typeof AccommodationRoute
  '/adventure': typeof AdventureRoute
  '/adventure-activities': typeof AdventureActivitiesRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/experiences': typeof ExperiencesRoute
  '/family': typeof FamilyRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/gallery': typeof GalleryRoute
  '/infinity-pool': typeof InfinityPoolRoute
  '/nearby-attractions': typeof NearbyAttractionsRoute
  '/offers': typeof OffersRouteWithChildren
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/resort-amenities': typeof ResortAmenitiesRoute
  '/restaurant': typeof RestaurantRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tariff': typeof TariffRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/weddings': typeof WeddingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/offers/monsoon': typeof OffersMonsoonRoute
  '/villas/$slug': typeof VillasSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/villas/': typeof VillasIndexRoute
  '/blog/category/$cat': typeof BlogCategoryCatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/accommodation'
    | '/adventure'
    | '/adventure-activities'
    | '/cancellation-policy'
    | '/contact'
    | '/corporate'
    | '/experiences'
    | '/family'
    | '/faq'
    | '/feedback'
    | '/gallery'
    | '/infinity-pool'
    | '/nearby-attractions'
    | '/offers'
    | '/packages'
    | '/privacy-policy'
    | '/refund-policy'
    | '/resort-amenities'
    | '/restaurant'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/tariff'
    | '/terms-and-conditions'
    | '/testimonials'
    | '/weddings'
    | '/blog/$slug'
    | '/offers/monsoon'
    | '/villas/$slug'
    | '/blog/'
    | '/villas/'
    | '/blog/category/$cat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/accommodation'
    | '/adventure'
    | '/adventure-activities'
    | '/cancellation-policy'
    | '/contact'
    | '/corporate'
    | '/experiences'
    | '/family'
    | '/faq'
    | '/feedback'
    | '/gallery'
    | '/infinity-pool'
    | '/nearby-attractions'
    | '/offers'
    | '/packages'
    | '/privacy-policy'
    | '/refund-policy'
    | '/resort-amenities'
    | '/restaurant'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/tariff'
    | '/terms-and-conditions'
    | '/testimonials'
    | '/weddings'
    | '/blog/$slug'
    | '/offers/monsoon'
    | '/villas/$slug'
    | '/blog'
    | '/villas'
    | '/blog/category/$cat'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/accommodation'
    | '/adventure'
    | '/adventure-activities'
    | '/cancellation-policy'
    | '/contact'
    | '/corporate'
    | '/experiences'
    | '/family'
    | '/faq'
    | '/feedback'
    | '/gallery'
    | '/infinity-pool'
    | '/nearby-attractions'
    | '/offers'
    | '/packages'
    | '/privacy-policy'
    | '/refund-policy'
    | '/resort-amenities'
    | '/restaurant'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/tariff'
    | '/terms-and-conditions'
    | '/testimonials'
    | '/weddings'
    | '/blog/$slug'
    | '/offers/monsoon'
    | '/villas/$slug'
    | '/blog/'
    | '/villas/'
    | '/blog/category/$cat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AccommodationRoute: typeof AccommodationRoute
  AdventureRoute: typeof AdventureRoute
  AdventureActivitiesRoute: typeof AdventureActivitiesRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  ExperiencesRoute: typeof ExperiencesRoute
  FamilyRoute: typeof FamilyRoute
  FaqRoute: typeof FaqRoute
  FeedbackRoute: typeof FeedbackRoute
  GalleryRoute: typeof GalleryRoute
  InfinityPoolRoute: typeof InfinityPoolRoute
  NearbyAttractionsRoute: typeof NearbyAttractionsRoute
  OffersRoute: typeof OffersRouteWithChildren
  PackagesRoute: typeof PackagesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResortAmenitiesRoute: typeof ResortAmenitiesRoute
  RestaurantRoute: typeof RestaurantRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TariffRoute: typeof TariffRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WeddingsRoute: typeof WeddingsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  VillasSlugRoute: typeof VillasSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  VillasIndexRoute: typeof VillasIndexRoute
  BlogCategoryCatRoute: typeof BlogCategoryCatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tariff': {
      id: '/tariff'
      path: '/tariff'
      fullPath: '/tariff'
      preLoaderRoute: typeof TariffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resort-amenities': {
      id: '/resort-amenities'
      path: '/resort-amenities'
      fullPath: '/resort-amenities'
      preLoaderRoute: typeof ResortAmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby-attractions': {
      id: '/nearby-attractions'
      path: '/nearby-attractions'
      fullPath: '/nearby-attractions'
      preLoaderRoute: typeof NearbyAttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infinity-pool': {
      id: '/infinity-pool'
      path: '/infinity-pool'
      fullPath: '/infinity-pool'
      preLoaderRoute: typeof InfinityPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventure-activities': {
      id: '/adventure-activities'
      path: '/adventure-activities'
      fullPath: '/adventure-activities'
      preLoaderRoute: typeof AdventureActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventure': {
      id: '/adventure'
      path: '/adventure'
      fullPath: '/adventure'
      preLoaderRoute: typeof AdventureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villas/': {
      id: '/villas/'
      path: '/villas'
      fullPath: '/villas/'
      preLoaderRoute: typeof VillasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villas/$slug': {
      id: '/villas/$slug'
      path: '/villas/$slug'
      fullPath: '/villas/$slug'
      preLoaderRoute: typeof VillasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/monsoon': {
      id: '/offers/monsoon'
      path: '/monsoon'
      fullPath: '/offers/monsoon'
      preLoaderRoute: typeof OffersMonsoonRouteImport
      parentRoute: typeof OffersRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$cat': {
      id: '/blog/category/$cat'
      path: '/blog/category/$cat'
      fullPath: '/blog/category/$cat'
      preLoaderRoute: typeof BlogCategoryCatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OffersRouteChildren {
  OffersMonsoonRoute: typeof OffersMonsoonRoute
}

const OffersRouteChildren: OffersRouteChildren = {
  OffersMonsoonRoute: OffersMonsoonRoute,
}

const OffersRouteWithChildren =
  OffersRoute._addFileChildren(OffersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AccommodationRoute: AccommodationRoute,
  AdventureRoute: AdventureRoute,
  AdventureActivitiesRoute: AdventureActivitiesRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  ExperiencesRoute: ExperiencesRoute,
  FamilyRoute: FamilyRoute,
  FaqRoute: FaqRoute,
  FeedbackRoute: FeedbackRoute,
  GalleryRoute: GalleryRoute,
  InfinityPoolRoute: InfinityPoolRoute,
  NearbyAttractionsRoute: NearbyAttractionsRoute,
  OffersRoute: OffersRouteWithChildren,
  PackagesRoute: PackagesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResortAmenitiesRoute: ResortAmenitiesRoute,
  RestaurantRoute: RestaurantRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TariffRoute: TariffRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TestimonialsRoute: TestimonialsRoute,
  WeddingsRoute: WeddingsRoute,
  BlogSlugRoute: BlogSlugRoute,
  VillasSlugRoute: VillasSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  VillasIndexRoute: VillasIndexRoute,
  BlogCategoryCatRoute: BlogCategoryCatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
